version: '3.8'
services:
  prod:
    build:
      context: .
      target: prod
    ports:
      - '4000:3000'
    expose:
      - '5000'
    container_name: node_app-prod
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: npm run start

  db:
    image: postgres:10.3
    container_name: postgres-Lakerol
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env

volumes:
  postgres_data:

