version: '3.8'
services:
  app:
      build: .
      ports:
        - '8080:8080'
  postgres:
    image: postgres:10.3
    container_name: postgres-Läkerol
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
