version: '3.8'
services:
  dev:
  app:
    build:
      context: .
      target: development # Käytä kehitysvaiheen kohdetta Dockerfilen määrittämiseen
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    expose:
      - '5000'
    env_file:
      - .env
    container_name: node_app
    volumes:
      - .:/app
    depends_on:
      - db
    command: npm run dev # Käynnistä Nodemon development-skriptillä

  production:
    build:
      context: .
      target: production # Käytä tuotantovaiheen kohdetta Dockerfilen määrittämiseen
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:10.3
    container_name: postgres-Lakerol
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env

volumes:
  postgres_data:

